<?php

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RolesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DEVELPER ROLE
        $role1 = Role::firstOrCreate([
		            'name' => 'Developer',
		            'title' => 'Developer Team',
		            'guard_name' => 'web'
		        ]);
       	$permissions1 = Permission::whereIn('name',[
            'role-list',
            'role-create',
            'role-edit',
            'role-delete',
            'permission-list',
            'permission-create',
            'permission-delete'
        ])->get();
       	$role1->syncPermissions($permissions1);
        
        // SUPER ADMIN ROLE
        $role2 = Role::firstOrCreate([
                    'name' => 'SuperAdmin',
                    'title' => 'Super Admin',
                    'guard_name' => 'web'
                ]);
        $permissions2 = Permission::whereIn('name',[
            'user-list',
            'user-create',
            'user-delete',
            'user-status',
            'country-list',
            'country-create',
            'country-edit',
            'country-delete',
            'country-status',
            'state-list',
            'state-create',
            'state-edit',
            'state-delete',
            'state-status',
            'city-list',
            'city-create',
            'city-edit',
            'city-delete',
            'city-status',
            'faq-list',
            'faq-create',
            'faq-edit',
            'faq-delete',
            'cms-list',
            'cms-create',
            'cms-edit',
            'cms-delete',
            'enquiry-list',
            'enquiry-show',
            'setting-list',
            'cuisine-list',
            'cuisine-create',
            'cuisine-edit',
            'cuisine-delete',
            'cuisine-status',
            /*'restaurant-list',
            'restaurant-create',
            'restaurant-edit',
            'restaurant-delete',
            'restaurant-status',
            'restaurant-show',
            'restaurant-branch-list',
            'restaurant-branch-create',
            'restaurant-branch-edit',
            'restaurant-branch-delete',
            'restaurant-branch-status',*/
            'news-list',
            'news-create',
            'news-edit',
            'news-delete',
            'news-status',
            'blog-list',
            /*'admin-list',
            'admin-create',
            'admin-edit',
            'admin-delete',
            'admin-status',
            'manager-list',
            'manager-create',
            'manager-edit',
            'manager-delete',
            'manager-status',*/
            'coupon-list',
            'coupon-create',
            'coupon-edit',
            'coupon-delete',
            'coupon-status',
            'seating-area-list',
            'seating-area-create',
            'seating-area-edit',
            'seating-area-delete',
            'seating-area-status',
            'reservation-list',
            /*'reservation-create',
            'reservation-edit',
            'reservation-status',*/
            /*'catering-list',
            'catering-create',
            'catering-edit',
            'catering-delete',
            'catering-status',
            'food-truck-list',
            'food-truck-create',
            'food-truck-edit',
            'food-truck-delete',
            'food-truck-status',
            'food-truck-branch-list',
            'food-truck-branch-create',
            'food-truck-branch-edit',
            'food-truck-branch-delete',
            'food-truck-branch-status',*/
            'company_details',
            'notifications',
            'subscription-package-list',
            'subscription-package-create',
            'subscription-package-edit',
            'subscription-package-delete',
            'subscription-package-status',
            'vendor-list',
            'vendor-create',
            'vendor-edit',
            'vendor-delete',
            'vendor-status',
            'business-list',
            'concern-list',
            'concern-create',
            'concern-edit',
            'concern-delete',
            'concern-status',
            'review-list',
            'review-status',
            'advertisement-list',
            'advertisement-create',
            'advertisement-edit',
            'advertisement-delete',
            'advertisement-status',
        ])->get();
        $role2->syncPermissions($permissions2);
        
        // ADMIN ROLE
        /*$role3 = Role::firstOrCreate([
		            'name' => 'Admin',
		            'title' => 'Admin',
		            'guard_name' => 'web'
		        ]);
        $permissions3 = Permission::whereIn('name',[
            'user-list',
            'user-create',
            'user-delete',
            'user-status',
            'country-list',
            'country-create',
            'country-edit',
            'country-delete',
            'country-status',
            'state-list',
            'state-create',
            'state-edit',
            'state-delete',
            'state-status',
            'city-list',
            'city-create',
            'city-edit',
            'city-delete',
            'city-status',
            'faq-list',
            'faq-create',
            'faq-edit',
            'faq-delete',
            'cms-list',
            'cms-create',
            'cms-edit',
            'cms-delete',
            'enquiry-list',
            'enquiry-show',
            'setting-list',
            'cuisine-list',
            'cuisine-create',
            'cuisine-edit',
            'cuisine-delete',
            'cuisine-status',
            'restaurant-list',
            'restaurant-create',
            'restaurant-edit',
            'restaurant-delete',
            'restaurant-status',
            'restaurant-show',
            'restaurant-branch-list',
            'restaurant-branch-create',
            'restaurant-branch-edit',
            'restaurant-branch-delete',
            'restaurant-branch-status',
            'news-list',
            'news-create',
            'news-edit',
            'news-delete',
            'news-status',
            'blog-list',
            'manager-list',
            'manager-create',
            'manager-edit',
            'manager-delete',
            'manager-status',
            'coupon-list',
            'coupon-create',
            'coupon-edit',
            'coupon-delete',
            'coupon-status',
            'seating-area-list',
            'seating-area-create',
            'seating-area-edit',
            'seating-area-delete',
            'seating-area-status',
            'reservation-list',
            'reservation-create',
            'reservation-edit',
            'reservation-status',
            'catering-list',
            'catering-create',
            'catering-edit',
            'catering-delete',
            'catering-status',
            'food-truck-list',
            'food-truck-create',
            'food-truck-edit',
            'food-truck-delete',
            'food-truck-status',
            'food-truck-branch-list',
            'food-truck-branch-create',
            'food-truck-branch-edit',
            'food-truck-branch-delete',
            'food-truck-branch-status',
            'company_details',
            'notifications',
        ])->get();
       	$role3->syncPermissions($permissions3);*/

        // Customer ROLE
        $role4 = Role::firstOrCreate([
		            'name' => 'Customer',
		            'title' => 'Customer',
		            'guard_name' => 'web'
		        ]);

        /*// Manager Role
        $role4 = Role::firstOrCreate([
                    'name' => 'Manager',
                    'title' => 'Manager',
                    'guard_name' => 'web'
                ]);
        $permissions3 = Permission::whereIn('name',[
            'restaurant-show',
            'restaurant-branch-list',
            // 'coupon-list',
            // 'coupon-create',
            // 'coupon-delete',
            // 'coupon-status',
            // 'seating-area-list',            
            'reservation-list',
            'reservation-create',
            'reservation-status'
        ])->get();
        $role4->syncPermissions($permissions3);*/


        // Vendor Role
        $role5 = Role::firstOrCreate([
                    'name' => 'Vendor',
                    'title' => 'Vendor/Food-Provider',
                    'guard_name' => 'web'
                ]);
        $permissions5 = Permission::whereIn('name',[
            'restaurant-show',
            // 'coupon-list',
            // 'coupon-create',
            // 'coupon-delete',
            // 'coupon-status',
            // 'seating-area-list',            
            'reservation-list',
            'reservation-edit',
            'reservation-create',
            'reservation-status',
            'business-create',
            'business-edit',
            'business-status',
            'business-branch-list',
            'business-branch-create',
            'business-branch-edit',
            'business-branch-delete',
            'business-branch-status',      
            'catering-plan-list',
            'catering-plan-create',
            'catering-plan-edit',
            'catering-plan-delete',
            'catering-plan-status',
            'catering-addon-list',
            'catering-addon-create',
            'catering-addon-edit',
            'catering-addon-delete',
            'catering-addon-status',
            'my-subscription',
            'reservation-hours-list',
            'reservation-hours-create',
            'reservation-hours-edit',
            'reservation-hours-delete',
            'reservation-hours-status',
            'menu-category-list',
            'menu-category-create',
            'menu-category-edit',
            'menu-category-delete',
            'menu-category-status',
            'menu-list',
            'menu-create',
            'menu-edit',
            'menu-delete',
            'menu-status',
            'pickup-hours-list',
            'pickup-hours-create',
            'pickup-hours-edit',
            'pickup-hours-delete',
            'pickup-hours-status',
            'staff-list',
            'staff-create',
            'staff-edit',
            'staff-delete',
            'staff-status',
            'catering-package-category-list',
            'catering-package-category-create',
            'catering-package-category-edit',
            'catering-package-category-status',
            'catering-package-list',
            'catering-package-create',
            'catering-package-edit',
            'catering-package-status',
            'one-view',
            'waiting-list',
            'pickups-order-list',
            'catering-order-list',
            'catering-order-create',
            'catering-order-delete',
            'catering-order-status',
        ])->get();
        $role5->syncPermissions($permissions5);

        // WaiterManager
        $role6 = Role::firstOrCreate([
                    'name' => 'WaiterManager',
                    'title' => 'Waiter/Manager',
                    'guard_name' => 'web'
                ]);
        $permissions6 = Permission::whereIn('name',[
            'waiting-list-list',
            'waiting-list-create',
            // 'waiting-list-delete',
            'waiting-list-status',
            'pickup-list',
            'pickup-create',
            // 'pickup-delete',
            'pickup-status',
            'reservation-list',
            'reservation-edit',
            'reservation-create',
            'reservation-status',
            'catering-order-list',
            'catering-order-create',
            // 'catering-order-delete',
            'catering-order-status',
            'one-view',
            'waiting-list',
            'pickups-order-list',
        ])->get();
        $role6->syncPermissions($permissions6);

    }
}
